---
- name: Include tasks for MacOS
  ansible.builtin.import_tasks: macos.yml
  when: ansible_system == "Darwin"

- name: Include tasks for Linux
  ansible.builtin.import_tasks: linux.yml
  when: ansible_system == "Linux"

- name: Set config paths as facts
  ansible.builtin.set_fact:
    ipsec_pki_path: /{{ tmpfs_volume_path }}/{{ tmpfs_volume_name }}/IPsec/

- name: Update config paths
  ansible.builtin.add_host:
    name: "{{ 'localhost' if cloud_instance_ip == 'localhost' else cloud_instance_ip }}"
    ipsec_pki_path: "{{ ipsec_pki_path }}"
