---
- name: Linux | Delete the PKI directory
  ansible.builtin.file:
    path: /{{ facts.tmpfs_volume_path }}/{{ facts.tmpfs_volume_name }}/
    state: absent
  when: facts.ansible_system == "Linux"

- name: Darwin
  when:
    - facts.ansible_system == "Darwin"
  block:
    - name: MacOS | check fs the ramdisk exists
      ansible.builtin.command: /usr/sbin/diskutil info "{{ facts.tmpfs_volume_name }}"
      ignore_errors: true
      changed_when: false
      register: diskutil_info

    - name: MacOS | unmount and eject the ram disk
      ansible.builtin.shell: >
        /usr/sbin/diskutil umount force "/{{ facts.tmpfs_volume_path }}/{{ facts.tmpfs_volume_name }}/" &&
        /usr/sbin/diskutil eject "{{ facts.tmpfs_volume_name }}"
      changed_when: false
      when: diskutil_info.rc == 0
      register: result
      until: result.rc == 0
      retries: 5
      delay: 3

