- local_action:
    module: azure
    name: my-virtual-machine
    role_size: Small
    image: b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu_DAILY_BUILD-precise-12_04_3-LTS-amd64-server-20131205-en-us-30GB
    location: 'East US'
    user: ubuntu
    ssh_cert_path: "/home/jack/.ssh/upwork.pub"
    storage_account: my-storage-account
    wait: yes
    subscription_id: "02e68d20-1a39-4faa-aa35-6bdd0238b54e"
    management_cert_path: "/home/jack/ownCloud/Clouds/azure/manage.cer"


#- name: "Creating a virtual machine..."
  #azure:
    #subscription_id: "02e68d20-1a39-4faa-aa35-6bdd0238b54e"
    #name: "algo-vpn"
    #role_size: Small
    #image: b39f27a8b8c64d52b05eac6a62ebad85__Ubuntu-16_04-LTS-amd64-server-20160721-en-us-30GB
    #location: "West Europe"
    #user: ubuntu
    #ssh_cert_path: "/home/jack/.ssh/upwork.pub"
    #storage_account: 'algo.vpn'
    #management_cert_path: "/home/jack/ownCloud/Clouds/azure/manage.cer"
    #wait: yes
    #state: present
  #register: azure_vm
  
- debug: msg="{{ azure_vm }}"  

#- name: Add the droplet to an inventory group
  #add_host:
    #name: "{{ do.droplet.ip_address }}"
    #groups: vpn-host
    #ansible_ssh_user: root
    #ansible_python_interpreter: "/usr/bin/python2.7"
    #do_access_token: "{{ do_access_token }}"
    #do_droplet_id: "{{ do.droplet.id }}"
    #dns_enabled: "{{ dns_enabled }}"
    #auditd_enabled: " {{ auditd_enabled }}"

#- name: Wait for SSH to become available
  #local_action: "wait_for port=22 host={{ do.droplet.ip_address }} timeout=320"

