- name: Add the instance to an inventory group
  add_host:
    name: "{{ server_ip }}"
    groups: vpn-host
    ansible_ssh_user: "{{ server_user }}"
    ansible_python_interpreter: "/usr/bin/python2.7"
    ansible_ssh_private_key_file: "{{ SSH_keys.private }}"
    cloud_provider: local
  when: server_ip != "localhost"

- name: Add the instance to an inventory group
  add_host:
    name: "{{ server_ip }}"
    groups: vpn-host
    ansible_ssh_user: "{{ server_user }}"
    ansible_python_interpreter: "/usr/bin/python2.7"
    ansible_ssh_private_key_file: "{{ SSH_keys.private }}"
    ansible_connection: local
    cloud_provider: local
  when: server_ip == "localhost"

- set_fact:
    cloud_instance_ip: "{{ server_ip }}"
