---
- name: Include prompts
  import_tasks: prompts.yml

- block:
  - name: Upload the SSH key
    vultr_ssh_key:
      name: "{{ SSH_keys.comment }}"
      ssh_key: "{{ lookup('file', '{{ SSH_keys.public }}') }}"
    register: ssh_key

  - name: Creating a firewall group
    vultr_firewall_group:
      name: "{{ algo_server_name }}"
 
  - name: Creating firewall rules
    vultr_firewall_rule:
      group: "{{ algo_server_name }}"
      protocol: udp
      port: "{{ item.port }}"
      cidr: "{{ item.cidr }}"
    with_items:
    - { port: 500, cidr: "0.0.0.0/0" }
    - { port: 500, cidr: "::/0" }
    - { port: 4500, cidr: "0.0.0.0/0" }
    - { port: 4500, cidr: "::/0" }
    - { port: 51820, cidr: "0.0.0.0/0" }
    - { port: 51820, cidr: "::/0" }
     
  - name: Creating a server
    vultr_server:
      name: "{{ algo_server_name }}"
      hostname: "{{ algo_server_name }}"
      os: "{{ cloud_providers.vultr.os }}"
      plan: "{{ cloud_providers.vultr.size }}"
      region: "{{ algo_vultr_region }}"
      firewall_group: "{{ algo_server_name }}"
      state: started
      tag: Environment:Algo
      ssh_key: "{{ ssh_key.vultr_ssh_key.name }}"
      ipv6_enabled: true
      auto_backup_enabled: false
      notify_activate: false
    register: vultr_server
    
  - set_fact:
      cloud_instance_ip: "{{ vultr_server.vultr_server.v4_main_ip }}"
      ansible_ssh_user: root

  environment:
    VULTR_API_CONFIG: "{{ algo_vultr_config }}"
