- name: restart rsyslog
  service: name=rsyslog state=restarted

- name: restart ipfw
  service: name=ipfw state=restarted

- name: flush routing cache
  shell: echo 1 > /proc/sys/net/ipv4/route/flush

- name: restart loopback bsd
  shell: >
    ifconfig lo100 destroy || true &&
    ifconfig lo100 create &&
    ifconfig lo100 inet {{ local_service_ip }} netmask 255.255.255.255 &&
    ifconfig lo100 inet6 FCAA::1/64; echo $?

- name: load dummy
  modprobe:
    name: dummy
    state: present
    params: 'numdummies=2'

- name: add dummy
  shell: ip link add dummy1 type dummy || /bin/true

- name: restart dummy
  shell: ifdown --force dummy1 && ifup dummy1
