---
- name: FreeBSD | Install prerequisites
  ansible.builtin.package:
    name:
      - python3
      - sudo
  vars:
    ansible_python_interpreter: /usr/local/bin/python2.7

- name: Set python3 as the interpreter to use
  ansible.builtin.set_fact:
    ansible_python_interpreter: /usr/local/bin/python3

- name: Gather facts
  ansible.builtin.setup:
- name: Gather additional facts
  ansible.builtin.import_tasks: facts.yml

- name: Set OS specific facts
  ansible.builtin.set_fact:
    config_prefix: /usr/local/
    strongswan_shell: /usr/sbin/nologin
    strongswan_home: /var/empty
    root_group: wheel
    ssh_service_name: sshd
    apparmor_enabled: false
    strongswan_additional_plugins:
      - kernel-pfroute
      - kernel-pfkey
    tools:
      - git
      - subversion
      - screen
      - coreutils
      - openssl
      - bash
      - wget
    sysctl:
      - item: net.inet.ip.forwarding
        value: 1
      - item: "{{ 'net.inet6.ip6.forwarding' if ipv6_support else none }}"
        value: 1

- name: Install tools
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ tools|default([]) }}"

- name: Loopback included into the rc config
  ansible.builtin.blockinfile:
    dest: /etc/rc.conf
    create: true
    block: |
      cloned_interfaces="lo100"
      ifconfig_lo100="inet {{ local_service_ip }} netmask 255.255.255.255"
      ifconfig_lo100_ipv6="inet6 {{ local_service_ipv6 }}/128"
  notify:
    - restart loopback bsd

- name: Enable the gateway features
  ansible.builtin.lineinfile:
    dest: /etc/rc.conf
    regexp: '^{{ item.param }}.*'
    line: '{{ item.param }}={{ item.value }}'
  with_items:
    - { param: firewall_enable, value: '"YES"' }
    - { param: firewall_type, value: '"open"' }
    - { param: gateway_enable, value: '"YES"' }
    - { param: natd_enable, value: '"YES"' }
    - { param: natd_interface, value: '"{{ ansible_default_ipv4.device|default() }}"' }
    - { param: natd_flags, value: '"-dynamic -m"' }
  notify:
    - restart ipfw

- name: FreeBSD | Activate IPFW
  ansible.builtin.shell: >
    kldstat -n ipfw.ko || kldload ipfw ; sysctl net.inet.ip.fw.enable=0 &&
    bash /etc/rc.firewall && sysctl net.inet.ip.fw.enable=1
  changed_when: false

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
