---
- block:
    - include_tasks: ubuntu.yml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - include_tasks: freebsd.yml
      when: ansible_distribution == 'FreeBSD'

    - include_tasks: arch.yml
      when: ansible_distribution == 'Archlinux'


    - name: Install tools
      package: name="{{ item }}" state=present
      with_items:
        - "{{ tools|default([]) }}"
      tags:
        - always

    - name: Sysctl tuning
      sysctl:
        name: "{{ item.item }}"
        value: "{{ item.value }}"
        sysctl_file: "{{ sysctl_file|default('/etc/sysctl.conf') }}"
      with_items:
        - "{{ sysctl|default([]) }}"
      tags:
        - always

    - meta: flush_handlers
  rescue:
    - debug: var=fail_hint
      tags: always
    - fail:
      tags: always
