---
- name: Check the system
  ansible.builtin.raw: uname -a
  register: OS
  changed_when: false
  tags:
    - update-users

- name: Fail
  ansible.builtin.fail:
  when: cloud_test|default(false)|bool

- name: Include ubuntu
  ansible.builtin.include_tasks: ubuntu.yml
  when: '"Ubuntu" in OS.stdout or "Linux" in OS.stdout'
  tags:
    - update-users

- name: Include freebsd
  ansible.builtin.include_tasks: freebsd.yml
  when: '"FreeBSD" in OS.stdout'
  tags:
    - update-users

- name: Sysctl tuning
  ansible.posix.sysctl:
    name: "{{ item.item }}"
    value: "{{ item.value }}"
  when: item.item
  with_items:
    - "{{ sysctl|default([]) }}"
  tags:
    - always

- ansible.builtin.meta: flush_handlers
