---
- name: Clean up the environment
  file:
    dest: "{{ hetzner_venv }}"
    state: absent
  when: clean_environment

- name: Install requirements
  pip:
    name:
      - hcloud
    state: latest
    virtualenv: "{{ hetzner_venv }}"
    virtualenv_python: python2.7
