- name: restart privoxy
  service: name=privoxy state=restarted

- name: daemon-reload
  shell: systemctl daemon-reload

- name: restart apparmor
  service: name=apparmor state=restarted

- name: restart apache2
  service: name=apache2 state=restarted

