- name: Enable IPv6 on the droplet
  uri:
    url: "https://api.digitalocean.com/v2/droplets/{{ do_droplet_id }}/actions"
    method: POST
    body:
      type: enable_ipv6
    body_format: json
    status_code: 201
    HEADER_Authorization: "Bearer {{ do_access_token }}"
    HEADER_Content-Type: "application/json"

- name: Get Droplet networks
  uri:
    url: "https://api.digitalocean.com/v2/droplets/{{ do_droplet_id }}"
    method: GET
    status_code: 200
    HEADER_Authorization: "Bearer {{ do_access_token }}"
    HEADER_Content-Type: "application/json"
  register: droplet_info

- name: IPv6 configured
  template: src=roles/cloud-digitalocean/templates/20-ipv6.cfg.j2 dest=/etc/network/interfaces.d/20-ipv6.cfg owner=root group=root mode=0644
  with_items: "{{ droplet_info.json.droplet.networks.v6 }}"
  notify:
    - reload eth0

- name: IPv6 included into the network config
  lineinfile: dest=/etc/network/interfaces line='source /etc/network/interfaces.d/20-ipv6.cfg' state=present
  notify:
    - reload eth0

- meta: flush_handlers

- name: Wait for SSH to become available
  local_action: "wait_for port=22 host={{ inventory_hostname }} timeout=320"
  become: false
