---

- name: Generate the SSH private key
  local_action: shell echo -e  'n' | ssh-keygen -b 2048 -C {{ SSH_keys.comment }} -t rsa -f {{ SSH_keys.private }} -q -N ""
  args:
    creates: configs/algo.pem

- name: Generate the SSH public key
  local_action: shell echo `ssh-keygen -y -f configs/algo.pem` {{ SSH_keys.comment }} > {{ SSH_keys.public }}
  args:
    creates: configs/algo.pem.pub

- name: Change mode for the SSH private key
  local_action: file path=configs/algo.pem mode=0600

- name: Ensure the dynamic inventory exists
  blockinfile:
    dest: configs/inventory.dynamic
    marker: "# {mark} ALGO MANAGED BLOCK"
    create: yes
    block: |
      [algo:children]
      {% for group in dynamic_inventory_groups %}
      {{ group }}
      {% endfor %}
